### ISSUE TITLE
cannot install.

### ISSUE THREAD

**Issue by qoli** [hideo55/node-unqlite#11]
cannot install.

```
Qoli-iMac:Server qoli$ npm install unqlite --save

> unqlite@0.3.5 install /Users/qoli/Programming/yanglam/Server/node_modules/unqlite
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/qoli/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:291:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:380:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:595:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qoli/Programming/yanglam/Server/node_modules/unqlite
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unqlite@0.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unqlite@0.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/qoli/.npm/_logs/2018-08-19T05_50_35_674Z-debug.log

```

**Comment by CodeSpent** [comment]
Same issue here, as well when using Runkit on NPM's site it states the package is unavailable despite that Runkit should have every package preinstalled. 

As well when trying to install by cloning the Github repository I'm met with the same error, so something is seriously wrong with this package. Looks like this issue was opened in August, should I assume this library is dead?
